/*
 * ClickUp API Reference
 * This is the ClickUp API Reference where you can learn about specific endpoints and parameters in detail.  Browse the available endpoints using the sidebar on the left.  **Not sure where to begin?** [Get Started with the ClickUp API](https://clickup.com/api) 
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for EditGuestOnWorkspacerequest
 */
public class EditGuestOnWorkspacerequestTest {
    private final EditGuestOnWorkspacerequest model = new EditGuestOnWorkspacerequest();

    /**
     * Model tests for EditGuestOnWorkspacerequest
     */
    @Test
    public void testEditGuestOnWorkspacerequest() {
        // TODO: test EditGuestOnWorkspacerequest
    }

    /**
     * Test the property 'username'
     */
    @Test
    public void usernameTest() {
        // TODO: test username
    }

    /**
     * Test the property 'canEditTags'
     */
    @Test
    public void canEditTagsTest() {
        // TODO: test canEditTags
    }

    /**
     * Test the property 'canSeeTimeSpent'
     */
    @Test
    public void canSeeTimeSpentTest() {
        // TODO: test canSeeTimeSpent
    }

    /**
     * Test the property 'canSeeTimeEstimated'
     */
    @Test
    public void canSeeTimeEstimatedTest() {
        // TODO: test canSeeTimeEstimated
    }

    /**
     * Test the property 'canCreateViews'
     */
    @Test
    public void canCreateViewsTest() {
        // TODO: test canCreateViews
    }

    /**
     * Test the property 'customRoleId'
     */
    @Test
    public void customRoleIdTest() {
        // TODO: test customRoleId
    }

}
