/*
 * ClickUp API Reference
 * This is the ClickUp API Reference where you can learn about specific endpoints and parameters in detail.  Browse the available endpoints using the sidebar on the left.  **Not sure where to begin?** [Get Started with the ClickUp API](https://clickup.com/api) 
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Assignees1;
import com.konfigthis.client.model.Checklists6;
import com.konfigthis.client.model.Creator5;
import com.konfigthis.client.model.CustomFields9;
import com.konfigthis.client.model.Folder3;
import com.konfigthis.client.model.List2;
import com.konfigthis.client.model.Project;
import com.konfigthis.client.model.Space;
import com.konfigthis.client.model.Status;
import com.konfigthis.client.model.Tags6;
import com.konfigthis.client.model.Watchers1;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Task3
 */
public class Task3Test {
    private final Task3 model = new Task3();

    /**
     * Model tests for Task3
     */
    @Test
    public void testTask3() {
        // TODO: test Task3
    }

    /**
     * Test the property 'tags'
     */
    @Test
    public void tagsTest() {
        // TODO: test tags
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'customId'
     */
    @Test
    public void customIdTest() {
        // TODO: test customId
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'textContent'
     */
    @Test
    public void textContentTest() {
        // TODO: test textContent
    }

    /**
     * Test the property 'markdownDescription'
     */
    @Test
    public void markdownDescriptionTest() {
        // TODO: test markdownDescription
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'orderindex'
     */
    @Test
    public void orderindexTest() {
        // TODO: test orderindex
    }

    /**
     * Test the property 'dateCreated'
     */
    @Test
    public void dateCreatedTest() {
        // TODO: test dateCreated
    }

    /**
     * Test the property 'dateUpdated'
     */
    @Test
    public void dateUpdatedTest() {
        // TODO: test dateUpdated
    }

    /**
     * Test the property 'dateClosed'
     */
    @Test
    public void dateClosedTest() {
        // TODO: test dateClosed
    }

    /**
     * Test the property 'dateDone'
     */
    @Test
    public void dateDoneTest() {
        // TODO: test dateDone
    }

    /**
     * Test the property 'creator'
     */
    @Test
    public void creatorTest() {
        // TODO: test creator
    }

    /**
     * Test the property 'assignees'
     */
    @Test
    public void assigneesTest() {
        // TODO: test assignees
    }

    /**
     * Test the property 'watchers'
     */
    @Test
    public void watchersTest() {
        // TODO: test watchers
    }

    /**
     * Test the property 'checklists'
     */
    @Test
    public void checklistsTest() {
        // TODO: test checklists
    }

    /**
     * Test the property 'parent'
     */
    @Test
    public void parentTest() {
        // TODO: test parent
    }

    /**
     * Test the property 'priority'
     */
    @Test
    public void priorityTest() {
        // TODO: test priority
    }

    /**
     * Test the property 'dueDate'
     */
    @Test
    public void dueDateTest() {
        // TODO: test dueDate
    }

    /**
     * Test the property 'startDate'
     */
    @Test
    public void startDateTest() {
        // TODO: test startDate
    }

    /**
     * Test the property 'points'
     */
    @Test
    public void pointsTest() {
        // TODO: test points
    }

    /**
     * Test the property 'timeEstimate'
     */
    @Test
    public void timeEstimateTest() {
        // TODO: test timeEstimate
    }

    /**
     * Test the property 'customFields'
     */
    @Test
    public void customFieldsTest() {
        // TODO: test customFields
    }

    /**
     * Test the property 'dependencies'
     */
    @Test
    public void dependenciesTest() {
        // TODO: test dependencies
    }

    /**
     * Test the property 'linkedTasks'
     */
    @Test
    public void linkedTasksTest() {
        // TODO: test linkedTasks
    }

    /**
     * Test the property 'teamId'
     */
    @Test
    public void teamIdTest() {
        // TODO: test teamId
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'permissionLevel'
     */
    @Test
    public void permissionLevelTest() {
        // TODO: test permissionLevel
    }

    /**
     * Test the property 'list'
     */
    @Test
    public void listTest() {
        // TODO: test list
    }

    /**
     * Test the property 'project'
     */
    @Test
    public void projectTest() {
        // TODO: test project
    }

    /**
     * Test the property 'folder'
     */
    @Test
    public void folderTest() {
        // TODO: test folder
    }

    /**
     * Test the property 'space'
     */
    @Test
    public void spaceTest() {
        // TODO: test space
    }

}
