/*
 * ClickUp API Reference
 * This is the ClickUp API Reference where you can learn about specific endpoints and parameters in detail.  Browse the available endpoints using the sidebar on the left.  **Not sure where to begin?** [Get Started with the ClickUp API](https://clickup.com/api) 
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Tracking
 */
public class TrackingTest {
    private final Tracking model = new Tracking();

    /**
     * Model tests for Tracking
     */
    @Test
    public void testTracking() {
        // TODO: test Tracking
    }

    /**
     * Test the property 'subtasks'
     */
    @Test
    public void subtasksTest() {
        // TODO: test subtasks
    }

    /**
     * Test the property 'checklists'
     */
    @Test
    public void checklistsTest() {
        // TODO: test checklists
    }

    /**
     * Test the property 'assignedComments'
     */
    @Test
    public void assignedCommentsTest() {
        // TODO: test assignedComments
    }

}
