/*
 * ClickUp API Reference
 * This is the ClickUp API Reference where you can learn about specific endpoints and parameters in detail.  Browse the available endpoints using the sidebar on the left.  **Not sure where to begin?** [Get Started with the ClickUp API](https://clickup.com/api) 
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * CreateListCommentrequest
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class CreateListCommentrequest {
  public static final String SERIALIZED_NAME_COMMENT_TEXT = "comment_text";
  @SerializedName(SERIALIZED_NAME_COMMENT_TEXT)
  private String commentText;

  public static final String SERIALIZED_NAME_ASSIGNEE = "assignee";
  @SerializedName(SERIALIZED_NAME_ASSIGNEE)
  private Integer assignee;

  public static final String SERIALIZED_NAME_NOTIFY_ALL = "notify_all";
  @SerializedName(SERIALIZED_NAME_NOTIFY_ALL)
  private Boolean notifyAll;

  public CreateListCommentrequest() {
  }

  public CreateListCommentrequest commentText(String commentText) {
    
    
    
    
    this.commentText = commentText;
    return this;
  }

   /**
   * Get commentText
   * @return commentText
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "List comment content", required = true, value = "")

  public String getCommentText() {
    return commentText;
  }


  public void setCommentText(String commentText) {
    
    
    
    this.commentText = commentText;
  }


  public CreateListCommentrequest assignee(Integer assignee) {
    
    
    
    
    this.assignee = assignee;
    return this;
  }

   /**
   * Get assignee
   * @return assignee
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "183", required = true, value = "")

  public Integer getAssignee() {
    return assignee;
  }


  public void setAssignee(Integer assignee) {
    
    
    
    this.assignee = assignee;
  }


  public CreateListCommentrequest notifyAll(Boolean notifyAll) {
    
    
    
    
    this.notifyAll = notifyAll;
    return this;
  }

   /**
   * If &#x60;notify_all&#x60; is true, notifications will be sent to everyone including the creator of the comment.
   * @return notifyAll
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "true", required = true, value = "If `notify_all` is true, notifications will be sent to everyone including the creator of the comment.")

  public Boolean getNotifyAll() {
    return notifyAll;
  }


  public void setNotifyAll(Boolean notifyAll) {
    
    
    
    this.notifyAll = notifyAll;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the CreateListCommentrequest instance itself
   */
  public CreateListCommentrequest putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateListCommentrequest createListCommentrequest = (CreateListCommentrequest) o;
    return Objects.equals(this.commentText, createListCommentrequest.commentText) &&
        Objects.equals(this.assignee, createListCommentrequest.assignee) &&
        Objects.equals(this.notifyAll, createListCommentrequest.notifyAll)&&
        Objects.equals(this.additionalProperties, createListCommentrequest.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(commentText, assignee, notifyAll, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateListCommentrequest {\n");
    sb.append("    commentText: ").append(toIndentedString(commentText)).append("\n");
    sb.append("    assignee: ").append(toIndentedString(assignee)).append("\n");
    sb.append("    notifyAll: ").append(toIndentedString(notifyAll)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("comment_text");
    openapiFields.add("assignee");
    openapiFields.add("notify_all");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("comment_text");
    openapiRequiredFields.add("assignee");
    openapiRequiredFields.add("notify_all");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to CreateListCommentrequest
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!CreateListCommentrequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CreateListCommentrequest is not found in the empty JSON string", CreateListCommentrequest.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CreateListCommentrequest.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("comment_text").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `comment_text` to be a primitive type in the JSON string but got `%s`", jsonObj.get("comment_text").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CreateListCommentrequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CreateListCommentrequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CreateListCommentrequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CreateListCommentrequest.class));

       return (TypeAdapter<T>) new TypeAdapter<CreateListCommentrequest>() {
           @Override
           public void write(JsonWriter out, CreateListCommentrequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public CreateListCommentrequest read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             CreateListCommentrequest instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of CreateListCommentrequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of CreateListCommentrequest
  * @throws IOException if the JSON string is invalid with respect to CreateListCommentrequest
  */
  public static CreateListCommentrequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CreateListCommentrequest.class);
  }

 /**
  * Convert an instance of CreateListCommentrequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

