/*
 * ClickUp API Reference
 * This is the ClickUp API Reference where you can learn about specific endpoints and parameters in detail.  Browse the available endpoints using the sidebar on the left.  **Not sure where to begin?** [Get Started with the ClickUp API](https://clickup.com/api) 
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * ProfileInfo
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class ProfileInfo {
  public static final String SERIALIZED_NAME_DISPLAY_PROFILE = "display_profile";
  @SerializedName(SERIALIZED_NAME_DISPLAY_PROFILE)
  private Object displayProfile = null;

  public static final String SERIALIZED_NAME_VERIFIED_AMBASSADOR = "verified_ambassador";
  @SerializedName(SERIALIZED_NAME_VERIFIED_AMBASSADOR)
  private Object verifiedAmbassador = null;

  public static final String SERIALIZED_NAME_VERIFIED_CONSULTANT = "verified_consultant";
  @SerializedName(SERIALIZED_NAME_VERIFIED_CONSULTANT)
  private Object verifiedConsultant = null;

  public static final String SERIALIZED_NAME_TOP_TIER_USER = "top_tier_user";
  @SerializedName(SERIALIZED_NAME_TOP_TIER_USER)
  private Object topTierUser = null;

  public static final String SERIALIZED_NAME_VIEWED_VERIFIED_AMBASSADOR = "viewed_verified_ambassador";
  @SerializedName(SERIALIZED_NAME_VIEWED_VERIFIED_AMBASSADOR)
  private Object viewedVerifiedAmbassador = null;

  public static final String SERIALIZED_NAME_VIEWED_VERIFIED_CONSULTANT = "viewed_verified_consultant";
  @SerializedName(SERIALIZED_NAME_VIEWED_VERIFIED_CONSULTANT)
  private Object viewedVerifiedConsultant = null;

  public static final String SERIALIZED_NAME_VIEWED_TOP_TIER_USER = "viewed_top_tier_user";
  @SerializedName(SERIALIZED_NAME_VIEWED_TOP_TIER_USER)
  private Object viewedTopTierUser = null;

  public ProfileInfo() {
  }

  public ProfileInfo displayProfile(Object displayProfile) {
    
    
    
    
    this.displayProfile = displayProfile;
    return this;
  }

   /**
   * Get displayProfile
   * @return displayProfile
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(required = true, value = "")

  public Object getDisplayProfile() {
    return displayProfile;
  }


  public void setDisplayProfile(Object displayProfile) {
    
    
    
    this.displayProfile = displayProfile;
  }


  public ProfileInfo verifiedAmbassador(Object verifiedAmbassador) {
    
    
    
    
    this.verifiedAmbassador = verifiedAmbassador;
    return this;
  }

   /**
   * Get verifiedAmbassador
   * @return verifiedAmbassador
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(required = true, value = "")

  public Object getVerifiedAmbassador() {
    return verifiedAmbassador;
  }


  public void setVerifiedAmbassador(Object verifiedAmbassador) {
    
    
    
    this.verifiedAmbassador = verifiedAmbassador;
  }


  public ProfileInfo verifiedConsultant(Object verifiedConsultant) {
    
    
    
    
    this.verifiedConsultant = verifiedConsultant;
    return this;
  }

   /**
   * Get verifiedConsultant
   * @return verifiedConsultant
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(required = true, value = "")

  public Object getVerifiedConsultant() {
    return verifiedConsultant;
  }


  public void setVerifiedConsultant(Object verifiedConsultant) {
    
    
    
    this.verifiedConsultant = verifiedConsultant;
  }


  public ProfileInfo topTierUser(Object topTierUser) {
    
    
    
    
    this.topTierUser = topTierUser;
    return this;
  }

   /**
   * Get topTierUser
   * @return topTierUser
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(required = true, value = "")

  public Object getTopTierUser() {
    return topTierUser;
  }


  public void setTopTierUser(Object topTierUser) {
    
    
    
    this.topTierUser = topTierUser;
  }


  public ProfileInfo viewedVerifiedAmbassador(Object viewedVerifiedAmbassador) {
    
    
    
    
    this.viewedVerifiedAmbassador = viewedVerifiedAmbassador;
    return this;
  }

   /**
   * Get viewedVerifiedAmbassador
   * @return viewedVerifiedAmbassador
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(required = true, value = "")

  public Object getViewedVerifiedAmbassador() {
    return viewedVerifiedAmbassador;
  }


  public void setViewedVerifiedAmbassador(Object viewedVerifiedAmbassador) {
    
    
    
    this.viewedVerifiedAmbassador = viewedVerifiedAmbassador;
  }


  public ProfileInfo viewedVerifiedConsultant(Object viewedVerifiedConsultant) {
    
    
    
    
    this.viewedVerifiedConsultant = viewedVerifiedConsultant;
    return this;
  }

   /**
   * Get viewedVerifiedConsultant
   * @return viewedVerifiedConsultant
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(required = true, value = "")

  public Object getViewedVerifiedConsultant() {
    return viewedVerifiedConsultant;
  }


  public void setViewedVerifiedConsultant(Object viewedVerifiedConsultant) {
    
    
    
    this.viewedVerifiedConsultant = viewedVerifiedConsultant;
  }


  public ProfileInfo viewedTopTierUser(Object viewedTopTierUser) {
    
    
    
    
    this.viewedTopTierUser = viewedTopTierUser;
    return this;
  }

   /**
   * Get viewedTopTierUser
   * @return viewedTopTierUser
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(required = true, value = "")

  public Object getViewedTopTierUser() {
    return viewedTopTierUser;
  }


  public void setViewedTopTierUser(Object viewedTopTierUser) {
    
    
    
    this.viewedTopTierUser = viewedTopTierUser;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the ProfileInfo instance itself
   */
  public ProfileInfo putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProfileInfo profileInfo = (ProfileInfo) o;
    return Objects.equals(this.displayProfile, profileInfo.displayProfile) &&
        Objects.equals(this.verifiedAmbassador, profileInfo.verifiedAmbassador) &&
        Objects.equals(this.verifiedConsultant, profileInfo.verifiedConsultant) &&
        Objects.equals(this.topTierUser, profileInfo.topTierUser) &&
        Objects.equals(this.viewedVerifiedAmbassador, profileInfo.viewedVerifiedAmbassador) &&
        Objects.equals(this.viewedVerifiedConsultant, profileInfo.viewedVerifiedConsultant) &&
        Objects.equals(this.viewedTopTierUser, profileInfo.viewedTopTierUser)&&
        Objects.equals(this.additionalProperties, profileInfo.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(displayProfile, verifiedAmbassador, verifiedConsultant, topTierUser, viewedVerifiedAmbassador, viewedVerifiedConsultant, viewedTopTierUser, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProfileInfo {\n");
    sb.append("    displayProfile: ").append(toIndentedString(displayProfile)).append("\n");
    sb.append("    verifiedAmbassador: ").append(toIndentedString(verifiedAmbassador)).append("\n");
    sb.append("    verifiedConsultant: ").append(toIndentedString(verifiedConsultant)).append("\n");
    sb.append("    topTierUser: ").append(toIndentedString(topTierUser)).append("\n");
    sb.append("    viewedVerifiedAmbassador: ").append(toIndentedString(viewedVerifiedAmbassador)).append("\n");
    sb.append("    viewedVerifiedConsultant: ").append(toIndentedString(viewedVerifiedConsultant)).append("\n");
    sb.append("    viewedTopTierUser: ").append(toIndentedString(viewedTopTierUser)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("display_profile");
    openapiFields.add("verified_ambassador");
    openapiFields.add("verified_consultant");
    openapiFields.add("top_tier_user");
    openapiFields.add("viewed_verified_ambassador");
    openapiFields.add("viewed_verified_consultant");
    openapiFields.add("viewed_top_tier_user");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("display_profile");
    openapiRequiredFields.add("verified_ambassador");
    openapiRequiredFields.add("verified_consultant");
    openapiRequiredFields.add("top_tier_user");
    openapiRequiredFields.add("viewed_verified_ambassador");
    openapiRequiredFields.add("viewed_verified_consultant");
    openapiRequiredFields.add("viewed_top_tier_user");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ProfileInfo
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!ProfileInfo.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ProfileInfo is not found in the empty JSON string", ProfileInfo.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ProfileInfo.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ProfileInfo.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ProfileInfo' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ProfileInfo> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ProfileInfo.class));

       return (TypeAdapter<T>) new TypeAdapter<ProfileInfo>() {
           @Override
           public void write(JsonWriter out, ProfileInfo value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public ProfileInfo read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             ProfileInfo instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ProfileInfo given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ProfileInfo
  * @throws IOException if the JSON string is invalid with respect to ProfileInfo
  */
  public static ProfileInfo fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ProfileInfo.class);
  }

 /**
  * Convert an instance of ProfileInfo to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

