/*
 * ClickUp API Reference
 * This is the ClickUp API Reference where you can learn about specific endpoints and parameters in detail.  Browse the available endpoints using the sidebar on the left.  **Not sure where to begin?** [Get Started with the ClickUp API](https://clickup.com/api) 
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Creator;
import com.konfigthis.client.model.Folder;
import com.konfigthis.client.model.LinkedTask;
import com.konfigthis.client.model.Space;
import com.konfigthis.client.model.Status;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * Task
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class Task {
  public static final String SERIALIZED_NAME_TAGS = "tags";
  @SerializedName(SERIALIZED_NAME_TAGS)
  private List<String> tags = new ArrayList<>();

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private Status status;

  public static final String SERIALIZED_NAME_ORDERINDEX = "orderindex";
  @SerializedName(SERIALIZED_NAME_ORDERINDEX)
  private String orderindex;

  public static final String SERIALIZED_NAME_DATE_CREATED = "date_created";
  @SerializedName(SERIALIZED_NAME_DATE_CREATED)
  private String dateCreated;

  public static final String SERIALIZED_NAME_DATE_UPDATED = "date_updated";
  @SerializedName(SERIALIZED_NAME_DATE_UPDATED)
  private String dateUpdated;

  public static final String SERIALIZED_NAME_DATE_CLOSED = "date_closed";
  @SerializedName(SERIALIZED_NAME_DATE_CLOSED)
  private Object dateClosed = null;

  public static final String SERIALIZED_NAME_CREATOR = "creator";
  @SerializedName(SERIALIZED_NAME_CREATOR)
  private Creator creator;

  public static final String SERIALIZED_NAME_ASSIGNEES = "assignees";
  @SerializedName(SERIALIZED_NAME_ASSIGNEES)
  private List<String> assignees = new ArrayList<>();

  public static final String SERIALIZED_NAME_CHECKLISTS = "checklists";
  @SerializedName(SERIALIZED_NAME_CHECKLISTS)
  private List<String> checklists = new ArrayList<>();

  public static final String SERIALIZED_NAME_PARENT = "parent";
  @SerializedName(SERIALIZED_NAME_PARENT)
  private Object parent = null;

  public static final String SERIALIZED_NAME_PRIORITY = "priority";
  @SerializedName(SERIALIZED_NAME_PRIORITY)
  private Object priority = null;

  public static final String SERIALIZED_NAME_DUE_DATE = "due_date";
  @SerializedName(SERIALIZED_NAME_DUE_DATE)
  private Object dueDate = null;

  public static final String SERIALIZED_NAME_START_DATE = "start_date";
  @SerializedName(SERIALIZED_NAME_START_DATE)
  private Object startDate = null;

  public static final String SERIALIZED_NAME_TIME_ESTIMATE = "time_estimate";
  @SerializedName(SERIALIZED_NAME_TIME_ESTIMATE)
  private Object timeEstimate = null;

  public static final String SERIALIZED_NAME_TIME_SPENT = "time_spent";
  @SerializedName(SERIALIZED_NAME_TIME_SPENT)
  private Object timeSpent = null;

  public static final String SERIALIZED_NAME_LIST = "list";
  @SerializedName(SERIALIZED_NAME_LIST)
  private List list;

  public static final String SERIALIZED_NAME_FOLDER = "folder";
  @SerializedName(SERIALIZED_NAME_FOLDER)
  private Folder folder;

  public static final String SERIALIZED_NAME_SPACE = "space";
  @SerializedName(SERIALIZED_NAME_SPACE)
  private Space space;

  public static final String SERIALIZED_NAME_LINKED_TASKS = "linked_tasks";
  @SerializedName(SERIALIZED_NAME_LINKED_TASKS)
  private List<LinkedTask> linkedTasks = new ArrayList<>();

  public static final String SERIALIZED_NAME_URL = "url";
  @SerializedName(SERIALIZED_NAME_URL)
  private String url;

  public Task() {
  }

  public Task tags(List<String> tags) {
    
    
    
    
    this.tags = tags;
    return this;
  }

  public Task addTagsItem(String tagsItem) {
    this.tags.add(tagsItem);
    return this;
  }

   /**
   * 
   * @return tags
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public List<String> getTags() {
    return tags;
  }


  public void setTags(List<String> tags) {
    
    
    
    this.tags = tags;
  }


  public Task id(String id) {
    
    
    
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "9hvX", required = true, value = "")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    
    
    
    this.id = id;
  }


  public Task name(String name) {
    
    
    
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "Task Name", required = true, value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    
    
    
    this.name = name;
  }


  public Task status(Status status) {
    
    
    
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Status getStatus() {
    return status;
  }


  public void setStatus(Status status) {
    
    
    
    this.status = status;
  }


  public Task orderindex(String orderindex) {
    
    
    
    
    this.orderindex = orderindex;
    return this;
  }

   /**
   * Get orderindex
   * @return orderindex
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "1.00000000000000000000000000000000", required = true, value = "")

  public String getOrderindex() {
    return orderindex;
  }


  public void setOrderindex(String orderindex) {
    
    
    
    this.orderindex = orderindex;
  }


  public Task dateCreated(String dateCreated) {
    
    
    
    
    this.dateCreated = dateCreated;
    return this;
  }

   /**
   * Get dateCreated
   * @return dateCreated
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "1567780450202", required = true, value = "")

  public String getDateCreated() {
    return dateCreated;
  }


  public void setDateCreated(String dateCreated) {
    
    
    
    this.dateCreated = dateCreated;
  }


  public Task dateUpdated(String dateUpdated) {
    
    
    
    
    this.dateUpdated = dateUpdated;
    return this;
  }

   /**
   * Get dateUpdated
   * @return dateUpdated
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "1567780450202", required = true, value = "")

  public String getDateUpdated() {
    return dateUpdated;
  }


  public void setDateUpdated(String dateUpdated) {
    
    
    
    this.dateUpdated = dateUpdated;
  }


  public Task dateClosed(Object dateClosed) {
    
    
    
    
    this.dateClosed = dateClosed;
    return this;
  }

   /**
   * Get dateClosed
   * @return dateClosed
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(required = true, value = "")

  public Object getDateClosed() {
    return dateClosed;
  }


  public void setDateClosed(Object dateClosed) {
    
    
    
    this.dateClosed = dateClosed;
  }


  public Task creator(Creator creator) {
    
    
    
    
    this.creator = creator;
    return this;
  }

   /**
   * Get creator
   * @return creator
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Creator getCreator() {
    return creator;
  }


  public void setCreator(Creator creator) {
    
    
    
    this.creator = creator;
  }


  public Task assignees(List<String> assignees) {
    
    
    
    
    this.assignees = assignees;
    return this;
  }

  public Task addAssigneesItem(String assigneesItem) {
    this.assignees.add(assigneesItem);
    return this;
  }

   /**
   * 
   * @return assignees
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public List<String> getAssignees() {
    return assignees;
  }


  public void setAssignees(List<String> assignees) {
    
    
    
    this.assignees = assignees;
  }


  public Task checklists(List<String> checklists) {
    
    
    
    
    this.checklists = checklists;
    return this;
  }

  public Task addChecklistsItem(String checklistsItem) {
    this.checklists.add(checklistsItem);
    return this;
  }

   /**
   * 
   * @return checklists
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public List<String> getChecklists() {
    return checklists;
  }


  public void setChecklists(List<String> checklists) {
    
    
    
    this.checklists = checklists;
  }


  public Task parent(Object parent) {
    
    
    
    
    this.parent = parent;
    return this;
  }

   /**
   * Get parent
   * @return parent
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(required = true, value = "")

  public Object getParent() {
    return parent;
  }


  public void setParent(Object parent) {
    
    
    
    this.parent = parent;
  }


  public Task priority(Object priority) {
    
    
    
    
    this.priority = priority;
    return this;
  }

   /**
   * Get priority
   * @return priority
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(required = true, value = "")

  public Object getPriority() {
    return priority;
  }


  public void setPriority(Object priority) {
    
    
    
    this.priority = priority;
  }


  public Task dueDate(Object dueDate) {
    
    
    
    
    this.dueDate = dueDate;
    return this;
  }

   /**
   * Get dueDate
   * @return dueDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(required = true, value = "")

  public Object getDueDate() {
    return dueDate;
  }


  public void setDueDate(Object dueDate) {
    
    
    
    this.dueDate = dueDate;
  }


  public Task startDate(Object startDate) {
    
    
    
    
    this.startDate = startDate;
    return this;
  }

   /**
   * Get startDate
   * @return startDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(required = true, value = "")

  public Object getStartDate() {
    return startDate;
  }


  public void setStartDate(Object startDate) {
    
    
    
    this.startDate = startDate;
  }


  public Task timeEstimate(Object timeEstimate) {
    
    
    
    
    this.timeEstimate = timeEstimate;
    return this;
  }

   /**
   * Get timeEstimate
   * @return timeEstimate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(required = true, value = "")

  public Object getTimeEstimate() {
    return timeEstimate;
  }


  public void setTimeEstimate(Object timeEstimate) {
    
    
    
    this.timeEstimate = timeEstimate;
  }


  public Task timeSpent(Object timeSpent) {
    
    
    
    
    this.timeSpent = timeSpent;
    return this;
  }

   /**
   * Get timeSpent
   * @return timeSpent
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(required = true, value = "")

  public Object getTimeSpent() {
    return timeSpent;
  }


  public void setTimeSpent(Object timeSpent) {
    
    
    
    this.timeSpent = timeSpent;
  }


  public Task list(List list) {
    
    
    
    
    this.list = list;
    return this;
  }

   /**
   * Get list
   * @return list
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public List getList() {
    return list;
  }


  public void setList(List list) {
    
    
    
    this.list = list;
  }


  public Task folder(Folder folder) {
    
    
    
    
    this.folder = folder;
    return this;
  }

   /**
   * Get folder
   * @return folder
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Folder getFolder() {
    return folder;
  }


  public void setFolder(Folder folder) {
    
    
    
    this.folder = folder;
  }


  public Task space(Space space) {
    
    
    
    
    this.space = space;
    return this;
  }

   /**
   * Get space
   * @return space
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Space getSpace() {
    return space;
  }


  public void setSpace(Space space) {
    
    
    
    this.space = space;
  }


  public Task linkedTasks(List<LinkedTask> linkedTasks) {
    
    
    
    
    this.linkedTasks = linkedTasks;
    return this;
  }

  public Task addLinkedTasksItem(LinkedTask linkedTasksItem) {
    this.linkedTasks.add(linkedTasksItem);
    return this;
  }

   /**
   * 
   * @return linkedTasks
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public List<LinkedTask> getLinkedTasks() {
    return linkedTasks;
  }


  public void setLinkedTasks(List<LinkedTask> linkedTasks) {
    
    
    
    this.linkedTasks = linkedTasks;
  }


  public Task url(String url) {
    
    
    
    
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "https://app.clickup.com/t/9hx", required = true, value = "")

  public String getUrl() {
    return url;
  }


  public void setUrl(String url) {
    
    
    
    this.url = url;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the Task instance itself
   */
  public Task putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Task task = (Task) o;
    return Objects.equals(this.tags, task.tags) &&
        Objects.equals(this.id, task.id) &&
        Objects.equals(this.name, task.name) &&
        Objects.equals(this.status, task.status) &&
        Objects.equals(this.orderindex, task.orderindex) &&
        Objects.equals(this.dateCreated, task.dateCreated) &&
        Objects.equals(this.dateUpdated, task.dateUpdated) &&
        Objects.equals(this.dateClosed, task.dateClosed) &&
        Objects.equals(this.creator, task.creator) &&
        Objects.equals(this.assignees, task.assignees) &&
        Objects.equals(this.checklists, task.checklists) &&
        Objects.equals(this.parent, task.parent) &&
        Objects.equals(this.priority, task.priority) &&
        Objects.equals(this.dueDate, task.dueDate) &&
        Objects.equals(this.startDate, task.startDate) &&
        Objects.equals(this.timeEstimate, task.timeEstimate) &&
        Objects.equals(this.timeSpent, task.timeSpent) &&
        Objects.equals(this.list, task.list) &&
        Objects.equals(this.folder, task.folder) &&
        Objects.equals(this.space, task.space) &&
        Objects.equals(this.linkedTasks, task.linkedTasks) &&
        Objects.equals(this.url, task.url)&&
        Objects.equals(this.additionalProperties, task.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tags, id, name, status, orderindex, dateCreated, dateUpdated, dateClosed, creator, assignees, checklists, parent, priority, dueDate, startDate, timeEstimate, timeSpent, list, folder, space, linkedTasks, url, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Task {\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    orderindex: ").append(toIndentedString(orderindex)).append("\n");
    sb.append("    dateCreated: ").append(toIndentedString(dateCreated)).append("\n");
    sb.append("    dateUpdated: ").append(toIndentedString(dateUpdated)).append("\n");
    sb.append("    dateClosed: ").append(toIndentedString(dateClosed)).append("\n");
    sb.append("    creator: ").append(toIndentedString(creator)).append("\n");
    sb.append("    assignees: ").append(toIndentedString(assignees)).append("\n");
    sb.append("    checklists: ").append(toIndentedString(checklists)).append("\n");
    sb.append("    parent: ").append(toIndentedString(parent)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("    dueDate: ").append(toIndentedString(dueDate)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    timeEstimate: ").append(toIndentedString(timeEstimate)).append("\n");
    sb.append("    timeSpent: ").append(toIndentedString(timeSpent)).append("\n");
    sb.append("    list: ").append(toIndentedString(list)).append("\n");
    sb.append("    folder: ").append(toIndentedString(folder)).append("\n");
    sb.append("    space: ").append(toIndentedString(space)).append("\n");
    sb.append("    linkedTasks: ").append(toIndentedString(linkedTasks)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("tags");
    openapiFields.add("id");
    openapiFields.add("name");
    openapiFields.add("status");
    openapiFields.add("orderindex");
    openapiFields.add("date_created");
    openapiFields.add("date_updated");
    openapiFields.add("date_closed");
    openapiFields.add("creator");
    openapiFields.add("assignees");
    openapiFields.add("checklists");
    openapiFields.add("parent");
    openapiFields.add("priority");
    openapiFields.add("due_date");
    openapiFields.add("start_date");
    openapiFields.add("time_estimate");
    openapiFields.add("time_spent");
    openapiFields.add("list");
    openapiFields.add("folder");
    openapiFields.add("space");
    openapiFields.add("linked_tasks");
    openapiFields.add("url");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("tags");
    openapiRequiredFields.add("id");
    openapiRequiredFields.add("name");
    openapiRequiredFields.add("status");
    openapiRequiredFields.add("orderindex");
    openapiRequiredFields.add("date_created");
    openapiRequiredFields.add("date_updated");
    openapiRequiredFields.add("date_closed");
    openapiRequiredFields.add("creator");
    openapiRequiredFields.add("assignees");
    openapiRequiredFields.add("checklists");
    openapiRequiredFields.add("parent");
    openapiRequiredFields.add("priority");
    openapiRequiredFields.add("due_date");
    openapiRequiredFields.add("start_date");
    openapiRequiredFields.add("time_estimate");
    openapiRequiredFields.add("time_spent");
    openapiRequiredFields.add("list");
    openapiRequiredFields.add("folder");
    openapiRequiredFields.add("space");
    openapiRequiredFields.add("linked_tasks");
    openapiRequiredFields.add("url");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to Task
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!Task.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Task is not found in the empty JSON string", Task.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : Task.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      // ensure the required json array is present
      if (jsonObj.get("tags") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("tags").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `tags` to be an array in the JSON string but got `%s`", jsonObj.get("tags").toString()));
      }
      if (!jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if (!jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      // validate the required field `status`
      Status.validateJsonObject(jsonObj.getAsJsonObject("status"));
      if (!jsonObj.get("orderindex").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `orderindex` to be a primitive type in the JSON string but got `%s`", jsonObj.get("orderindex").toString()));
      }
      if (!jsonObj.get("date_created").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `date_created` to be a primitive type in the JSON string but got `%s`", jsonObj.get("date_created").toString()));
      }
      if (!jsonObj.get("date_updated").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `date_updated` to be a primitive type in the JSON string but got `%s`", jsonObj.get("date_updated").toString()));
      }
      // validate the required field `creator`
      Creator.validateJsonObject(jsonObj.getAsJsonObject("creator"));
      // ensure the required json array is present
      if (jsonObj.get("assignees") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("assignees").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `assignees` to be an array in the JSON string but got `%s`", jsonObj.get("assignees").toString()));
      }
      // ensure the required json array is present
      if (jsonObj.get("checklists") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("checklists").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `checklists` to be an array in the JSON string but got `%s`", jsonObj.get("checklists").toString()));
      }
      // validate the required field `list`
      List.validateJsonObject(jsonObj.getAsJsonObject("list"));
      // validate the required field `folder`
      Folder.validateJsonObject(jsonObj.getAsJsonObject("folder"));
      // validate the required field `space`
      Space.validateJsonObject(jsonObj.getAsJsonObject("space"));
      // ensure the json data is an array
      if (!jsonObj.get("linked_tasks").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `linked_tasks` to be an array in the JSON string but got `%s`", jsonObj.get("linked_tasks").toString()));
      }

      JsonArray jsonArraylinkedTasks = jsonObj.getAsJsonArray("linked_tasks");
      // validate the required field `linked_tasks` (array)
      for (int i = 0; i < jsonArraylinkedTasks.size(); i++) {
        LinkedTask.validateJsonObject(jsonArraylinkedTasks.get(i).getAsJsonObject());
      };
      if (!jsonObj.get("url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("url").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Task.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Task' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Task> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Task.class));

       return (TypeAdapter<T>) new TypeAdapter<Task>() {
           @Override
           public void write(JsonWriter out, Task value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public Task read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             Task instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of Task given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of Task
  * @throws IOException if the JSON string is invalid with respect to Task
  */
  public static Task fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Task.class);
  }

 /**
  * Convert an instance of Task to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

