/*
 * ClickUp API Reference
 * This is the ClickUp API Reference where you can learn about specific endpoints and parameters in detail.  Browse the available endpoints using the sidebar on the left.  **Not sure where to begin?** [Get Started with the ClickUp API](https://clickup.com/api) 
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.AddGuestToFolderrequest;
import com.konfigthis.client.model.AddGuestToFolderresponse;
import com.konfigthis.client.model.AddGuestToListrequest;
import com.konfigthis.client.model.AddGuestToListresponse;
import com.konfigthis.client.model.AddGuestToTaskrequest;
import com.konfigthis.client.model.AddGuestToTaskresponse;
import com.konfigthis.client.model.EditGuestOnWorkspacerequest;
import com.konfigthis.client.model.EditGuestOnWorkspaceresponse;
import com.konfigthis.client.model.InviteGuestToWorkspacerequest;
import com.konfigthis.client.model.InviteGuestToWorkspaceresponse;
import com.konfigthis.client.model.RemoveGuestFromFolderresponse;
import com.konfigthis.client.model.RemoveGuestFromListresponse;
import com.konfigthis.client.model.RemoveGuestFromTaskresponse;
import com.konfigthis.client.model.RemoveGuestFromWorkspaceresponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for GuestsApi
 */
@Disabled
public class GuestsApiTest {

    private static GuestsApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new GuestsApi(apiClient);
    }

    /**
     * Add Guest To Folder
     *
     * Share a Folder with a guest. \\  \\ ***Note:** This endpoint is only available to Workspaces on our [Enterprise Plan](https://clickup.com/pricing).*
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void addGuestToFolderTest() throws ApiException {
        String permissionLevel = null;
        Double folderId = null;
        Double guestId = null;
        Boolean includeShared = null;
        AddGuestToFolderresponse response = api.addGuestToFolder(permissionLevel, folderId, guestId)
                .includeShared(includeShared)
                .execute();
        // TODO: test validations
    }

    /**
     * Add Guest To Task
     *
     * Share a task with a guest. \\  \\ ***Note:** This endpoint is only available to Workspaces on our [Enterprise Plan](https://clickup.com/pricing).*
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void addToTaskTest() throws ApiException {
        String permissionLevel = null;
        String taskId = null;
        Double guestId = null;
        Boolean includeShared = null;
        Boolean customTaskIds = null;
        Double teamId = null;
        AddGuestToTaskresponse response = api.addToTask(permissionLevel, taskId, guestId)
                .includeShared(includeShared)
                .customTaskIds(customTaskIds)
                .teamId(teamId)
                .execute();
        // TODO: test validations
    }

    /**
     * Edit Guest On Workspace
     *
     * Rename and configure options for a guest. \\  \\ ***Note:** This endpoint is only available to Workspaces on our [Enterprise Plan](https://clickup.com/pricing).*
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void editGuestOnWorkspaceTest() throws ApiException {
        String username = null;
        Boolean canEditTags = null;
        Boolean canSeeTimeSpent = null;
        Boolean canSeeTimeEstimated = null;
        Boolean canCreateViews = null;
        Integer customRoleId = null;
        Double teamId = null;
        Double guestId = null;
        EditGuestOnWorkspaceresponse response = api.editGuestOnWorkspace(username, canEditTags, canSeeTimeSpent, canSeeTimeEstimated, canCreateViews, customRoleId, teamId, guestId)
                .execute();
        // TODO: test validations
    }

    /**
     * Get Guest
     *
     * View information about a guest. \\  \\ ***Note:** This endpoint is only available to Workspaces on our [Enterprise Plan](https://clickup.com/pricing).*
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getGuestInformationTest() throws ApiException {
        Double teamId = null;
        Double guestId = null;
        Object response = api.getGuestInformation(teamId, guestId)
                .execute();
        // TODO: test validations
    }

    /**
     * Invite Guest To Workspace
     *
     * Invite a guest to join a Workspace. To invite a member to your Workspace, use the [Invite User to Workspace](https://clickup.com/api/clickupreference/operation/InviteUserToWorkspace/) endpoint. \\  \\ You&#39;ll also need to grant the guest access to specific items using the following endpoints: [Add Guest to Folder](clickupreference/operation/AddGuestToFolder/), [Add Guest to List](clickupreference/operation/AddGuestToList/), or [Add Guest to Task](clickupreference/operation/AddGuestToTask/). \\  \\ ***Note:** This endpoint is only available to Workspaces on our [Enterprise Plan](https://clickup.com/pricing).*
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void inviteToWorkspaceTest() throws ApiException {
        String email = null;
        Boolean canEditTags = null;
        Boolean canSeeTimeSpent = null;
        Boolean canSeeTimeEstimated = null;
        Boolean canCreateViews = null;
        Integer customRoleId = null;
        Double teamId = null;
        InviteGuestToWorkspaceresponse response = api.inviteToWorkspace(email, canEditTags, canSeeTimeSpent, canSeeTimeEstimated, canCreateViews, customRoleId, teamId)
                .execute();
        // TODO: test validations
    }

    /**
     * Remove Guest From List
     *
     * Revoke a guest&#39;s access to a List.\\  \\ ***Note:** This endpoint is only available to Workspaces on our [Enterprise Plan](https://clickup.com/pricing).*
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void removeFromListTest() throws ApiException {
        Double listId = null;
        Double guestId = null;
        Boolean includeShared = null;
        RemoveGuestFromListresponse response = api.removeFromList(listId, guestId)
                .includeShared(includeShared)
                .execute();
        // TODO: test validations
    }

    /**
     * Remove Guest From Folder
     *
     * Revoke a guest&#39;s access to a Folder. \\  \\ ***Note:** This endpoint is only available to Workspaces on our [Enterprise Plan](https://clickup.com/pricing).*
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void revokeAccessFromFolderTest() throws ApiException {
        Double folderId = null;
        Double guestId = null;
        Boolean includeShared = null;
        RemoveGuestFromFolderresponse response = api.revokeAccessFromFolder(folderId, guestId)
                .includeShared(includeShared)
                .execute();
        // TODO: test validations
    }

    /**
     * Remove Guest From Task
     *
     * Revoke a guest&#39;s access to a task. \\  \\ ***Note:** This endpoint is only available to Workspaces on our [Enterprise Plan](https://clickup.com/pricing).*
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void revokeAccessToTaskTest() throws ApiException {
        String taskId = null;
        Double guestId = null;
        Boolean includeShared = null;
        Boolean customTaskIds = null;
        Double teamId = null;
        RemoveGuestFromTaskresponse response = api.revokeAccessToTask(taskId, guestId)
                .includeShared(includeShared)
                .customTaskIds(customTaskIds)
                .teamId(teamId)
                .execute();
        // TODO: test validations
    }

    /**
     * Remove Guest From Workspace
     *
     * Revoke a guest&#39;s access to a Workspace. \\  \\ ***Note:** This endpoint is only available to Workspaces on our [Enterprise Plan](https://clickup.com/pricing).*
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void revokeGuestAccessToWorkspaceTest() throws ApiException {
        Double teamId = null;
        Double guestId = null;
        RemoveGuestFromWorkspaceresponse response = api.revokeGuestAccessToWorkspace(teamId, guestId)
                .execute();
        // TODO: test validations
    }

    /**
     * Add Guest To List
     *
     * Share a List with a guest. \\  \\ ***Note:** This endpoint is only available to Workspaces on our [Enterprise Plan](https://clickup.com/pricing).*
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void shareListWithTest() throws ApiException {
        String permissionLevel = null;
        Double listId = null;
        Double guestId = null;
        Boolean includeShared = null;
        AddGuestToListresponse response = api.shareListWith(permissionLevel, listId, guestId)
                .includeShared(includeShared)
                .execute();
        // TODO: test validations
    }

}
